apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: https://github.com/search?q=nginx+ingress+redirect+permanent
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: {{ .Values.srcCodeSearchHost }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
    - secretName: {{ .Release.Name }}-tls 
      hosts:
        - {{ .Values.srcCodeSearchHost }}

...