name: default
run-name: Continuous Integration
on:
  push:
#    branches-ignore:    
#      - main
  pull_request:
jobs:
  # --------------------------------------------
  build:
    name: Artifact build
    strategy:
      matrix:
        operatingSystem: [ubuntu-24.04]
      fail-fast: false
    runs-on: ${{ matrix.operatingSystem }}
    # 
    steps:
    - uses: actions/checkout@v3
    - uses: azure/setup-helm@v4
      with:
        version: 'latest'
    - name: Helm Chart
      run: |
        cd helm 
        # Get the list of files that have changed
        git diff-tree --relative --no-commit-id --name-only -r ${{ github.ref_name }}
        
        
        # Lint all charts
        for chart in $(find . -name Chart.yaml -exec dirname {} \;); do
          echo $chart
          helm lint $chart
        done